### ISSUE TITLE
hcat fails to max-project multi-page tiff

### ISSUE THREAD

**Issue by buswinka** [indzhykulianlab/hcat#2]
### Discussed in https://github.com/indzhykulianlab/hcat/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **twonius** October 31, 2022</sup>
I'm having trouble loading my images. I'm probably not setting up the images correctly here. 

I've limited it to two channels but now it seems to be throwing an error because it's trying to ensure at least 3 colors. 

Am i using an incorrect file format here? 
https://drive.google.com/drive/folders/1G96x6TBrInL5V8I_VeVVjFm_jaRFzlW8?usp=share_link

```

0, ['C:/Users/anton/Documents/HCAT\\Composite.tif']
Traceback (most recent call last):
  File "C:\Users\anton\anaconda3\envs\hcat\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\anton\anaconda3\envs\hcat\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\anton\anaconda3\envs\hcat\Scripts\hcat.exe\__main__.py", line 7, in <module>
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\click\core.py", line 1635, in invoke
    rv = super().invoke(ctx)
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\hcat\main.py", line 21, in cli
    gui().main_loop()
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\hcat\detect_gui.py", line 209, in main_loop
    self.load_image(self.valid_image_files[self.current_image_index])
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\hcat\detect_gui.py", line 348, in load_image
    self.raw_image: Tensor = hcat.lib.utils.make_rgb(self.raw_image)  # Ensure at least 3 colors
  File "C:\Users\anton\anaconda3\envs\hcat\lib\site-packages\hcat\lib\utils.py", line 529, in make_rgb
    _, x, y = image.shape
ValueError: too many values to unpack (expected 3)
```</div>

**Comment by buswinka** [comment]
[https://github.com/indzhykulianlab/hcat/commit/0d258d6b293765770687d5f5b4d4f919266fb2a4](url)
